### ISSUE TITLE
New tool to generate documentation?

### ISSUE THREAD

**Issue by marienfressinaud** [FreshRSS/documentation#5]
We were using [daux.io](http://daux.io/) until now to generate documentation from this repository but it is still not able to support image serving.

I suggested [couscous.io](http://couscous.io/) in my [community process ticket](https://github.com/FreshRSS/FreshRSS/issues/789) which is used by wallabag but after some tries, I'm not convinced.

I will now have a look to… Pelican! It could be great to have only one tool for both website and documentation. At least, I'm sure about its flexibility, support and I know how to use it. A problem is it is not destined fur such a usage but I'll try.

**Comment by marienfressinaud** [comment]
I'm now looking at http://www.mkdocs.org/

Multi-language is not supported yet but I think we can manage with sub-domains / sub-directories.

**Comment by marienfressinaud** [comment]
![capture d ecran de 2015-07-11 12-34-32](https://cloud.githubusercontent.com/assets/1436309/8633452/4bb0b7e2-27c9-11e5-8cb9-de00b142726c.png)

Images are back, and the design is a lot better :).

**Comment by Alkarex** [comment]
:+1:

**Comment by marienfressinaud** [comment]
You can have a look to what it looks now at http://dev.doc.freshrss.org/

My work is available at https://github.com/marienfressinaud/documentation/tree/mkdocs

**Comment by marienfressinaud** [comment]
It's online! :)
